name: Page CI

on:
    push:
        branches: [ "master" ]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup Node js
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   run: npm install
            -   run: npm run build
            -   name: Keep only website
                run: rm -R assets/ node_modules/ .gitignore package.json package-lock.json README.md
            -   name: Archive artifacts
                uses: actions/upload-pages-artifact@v3
                with:
                    path: .

    deploy:
        runs-on: ubuntu-latest

        needs: build

        steps:
            -   name: Setup Pages
                uses: actions/configure-pages@v5
            -   name: Deploy to GitHub Pages
                uses: actions/deploy-pages@v4
